# Generated by Django 4.2.7 on 2024-05-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_release',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата выхода продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='модель'),
        ),
    ]
