# Generated by Django 4.2.7 on 2024-05-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_branch_products_branch_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data_release',
            new_name='date_release',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='house_nomber',
            new_name='house_number',
        ),
    ]
